name: all_action
on:
  push:
    branches: [main]
  workflow_run:
    workflows: [Trigger all_action workflow]
    types: completed
  workflow_dispatch:

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print event name and workflow run conclusion
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"

  all_process:
    runs-on: windows-latest
    if: ${{ github.event_name == 'push' && success() }}
    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB_2 }}
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run code
        run: |
          python ./code/craw_data.py

        continue-on-error: true

      - name: Commit and push
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -m "updated"
          git push

  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger all_action repository dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.API_TOKEN_GITHUB_2 }}
          repository: ${{ github.repository }}
          event-type: all_action
