name: all_action
'on':
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch: # 添加一个可以手动运行的按钮
jobs:
  all_process: # 处理所有数据
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses: actions/checkout@v3
      - name: set up Python 3.10
        uses: actions/setup-Python@v4
        with:
          python-version: '3.10'
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run code
        run: python ./code/craw.py
      - name: commit and push
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          git commit -m "updated"
          git push